// Redux action constants.

// Data source constants.
export const DATASOURCE = 'DATASOURCE';
export const DATASOURCEREQUEST = 'DATASOURCEREQUEST';
export const DATASOURCESUCCESS = 'DATASOURCESUCCESS';
export const DATASOURCEFAILURE = 'DATASOURCEFAILURE';

export const CONNECTIONTYPE = 'CONNECTIONTYPE';
export const CONNECTIONTYPEREQUEST = 'CONNECTIONTYPEREQUEST';
export const CONNECTIONTYPESUCCESS = 'CONNECTIONTYPESUCCESS';
export const CONNECTIONTYPEFAILURE = 'CONNECTIONTYPEFAILURE';

export const TESTCONNECTION = 'TESTCONNECTION';
export const TESTCONNECTIONREQUEST = 'TESTCONNECTIONREQUEST';
export const TESTCONNECTIONSUCCESS = 'TESTCONNECTIONSUCCESS';
export const TESTCONNECTIONFAILURE = 'TESTCONNECTIONFAILURE';

export const CREATEDATASOURCE = 'CREATEDATASOURCE';
export const CREATEDATASOURCEREQUEST = 'CREATEDATASOURCEREQUEST';
export const CREATEDATASOURCESUCCESS = 'CREATEDATASOURCESUCCESS';
export const CREATEDATASOURCEFAILURE = 'CREATEDATASOURCEFAILURE';
// KPI Explorer constans.
export const KPIEXPLORER = 'KPIEXPLORER';
export const KPIEXPLORERREQUEST = 'KPIEXPLORERREQUEST';
export const KPIEXPLORERSUCCESS = 'KPIEXPLORERSUCCESS';
export const KPIEXPLORERFAILURE = 'KPIEXPLORERFAILURE';

export const KPIEXPLORERFORM = 'KPIEXPLORERFORM';
export const KPIEXPLORERFORMREQUEST = 'KPIEXPLORERFORMREQUEST';
export const KPIEXPLORERFORMSUCCESS = 'KPIEXPLORERFORMSUCCESS';
export const KPIEXPLORERFORMFAILURE = 'KPIEXPLORERFORMFAILURE';

export const KPIEXPLORERFIELDREQUEST = 'KPIEXPLORERFIELDREQUEST';
export const KPIEXPLORERFIELDSUCCESS = 'KPIEXPLORERFIELDSUCCESS';
export const KPIEXPLORERFIELDFAILURE = 'KPIEXPLORERFIELDFAILURE';

export const KPIEXPLORERSUBMITREQUEST = 'KPIEXPLORERSUBMITREQUEST';
export const KPIEXPLORERSUBMITSUCCESS = 'KPIEXPLORERSUBMITSUCCESS';
export const KPIEXPLORERSUBMITFAILURE = 'KPIEXPLORERSUBMITFAILURE';

export const DELETEDATASOURCE = 'DELETEDATASOURCE';
export const DELETEDATASOURCEREQUEST = 'DELETEDATASOURCEREQUEST';
export const DELETEDATASOURCESUCSESS = 'DELETEDATASOURCESUCCESS';
export const DELETEDATASOURCEFAILURE = 'DELETEDATASOURCEFAILURE';

export const DASHBOARDSIDEBAR = 'DASHBOARDSIDEBAR';
export const DASHBOARDSIDEBARREQUEST = 'DASHBOARDSIDEBARREQUEST';
export const DASHBOARDSIDEBARSUCCESS = 'DASHBOARDSIDEBARSUCCESS';
export const DASHBOARDSIDEBARFAILURE = 'DASHBOARDSIDEBARFAILURE';

export const DASHBOARDAGGREGATION = 'DASHBOARDAGGREGATION';
export const DASHBOARDAGGREGATIONSUCCESS = 'DASHBOARDAGGREGATION';
export const DASHBOARDAGGREGATIONREQUEST = 'DASHBOARDAGGREGATIONREQUEST';
export const DASHBOARDAGGREGATIONFAILURE = 'DASHBOARDAGGREGATIONFAILURE';

export const DASHBOARDLINECHART = 'DASHBOARDLINECHART';
export const DASHBOARDLINECHARTREQUEST = 'DASHBOARDLINECHARTREQUEST';
export const DASHBOARDLINECHARTSUCCESS = 'DASHBOARDLINECHARTSUCCESS';
export const DASHBOARDLINECHARTFAILURE = 'DASHBOARDLINECHARTFAILURE';

export const DASHBOARDRCAANALYSIS = 'DASBOARDRCAANALYSIS';
export const DASHBOARDRCAANALYSISREQUEST = 'DASHBOARDRCAANALYSISREQUEST';
export const DASHBOARDRCAANALYSISSUCCESS = 'DASHBOARDRCAANALYSISSUCCESS';
export const DASHBOARDRCAANALYSISFAILURE = 'DASHBOARDRCAANALYSISFAILURE';

export const DASHBOARDDIMENSION = 'DASHBOARDDIMENSION';
export const DASHBOARDDIMENSIONREQUEST = 'DASHBOARDDIMENSIONREQUEST';
export const DASHBOARDDIMENSIONSUCCESS = 'DASHBOARDDIMENSIONSUCCESS';
export const DASHBOARDDIMENSIONFAILURE = 'DASHBOARDDIMENSIONFAILURE';

export const DASHBOARDHIERARCHICAL = 'DASHBOARDHIERARCHICAL';
export const DASHBOARDHIERARCHICALSUCCESS = 'DASHBOARDHIERARCHICALSUCCESS';
export const DASHBOARDHIERARCHICALREQUEST = 'DASHBOARDHIERARCHICALREQUEST';
export const DASHBOARDHIERARCHICALFAILURE = 'DASHBOARDHIERARCHICALFAILURE';

export const ONBOARDING = 'ONBOARDING';
export const ONBOARDINGREQUEST = 'ONBOARDINGREQUEST';
export const ONBOARDINGSUCCESS = 'ONBOARDINGSUCCESS';
export const ONBOARDINGFAILURE = 'ONBOARDINGFAILURE';

export const TESTQUERY = 'TESTQUERY';
export const TESTQUERYREQUEST = 'TESTQUERYREQUEST';
export const TESTQUERYSUCCESS = 'TESTQUERYSUCCESS';
export const TESTQUERYFAILURE = 'TESTQUERYFAILURE';

export const ANOMALYDETECTION = 'ANOMALYDETECTION';
export const ANOMALYDETECTIONREQUEST = 'ANOMALYDETECTIONREQUEST';
export const ANOMALYDETECTIONSUCCESS = 'ANOMALYDETECTIONSUCCESS';
export const ANOMALYDETECTIONFAILURE = 'ANOMALYDETECTIONFAILURE';

export const ANOMALYDATAQUALITY = 'ANOMALYDATAQUALITY';
export const ANOMALYDATAQUALITYREQUEST = 'ANOMALYDATAQUALITYREQUEST';
export const ANOMALYDATAQUALITYSUCCESS = 'ANOMALYDATAQUALITYSUCCESS';
export const ANOMALYDATAQUALITYFAILURE = 'ANOMALYDATAQUALITYFAILURE';

export const ANOMALYDRILLDOWN = 'ANOMALYDRILLDOWN';
export const ANOMALYDRILLDOWNREQUEST = 'ANOMALYDRILLDOWNREQUEST';
export const ANOMALYDRILLDOWNSUCCESS = 'ANOMALYDRILLDOWNSUCCESS';
export const ANOMALYDRILLDOWNFAILURE = 'ANOMALYDRILLDOWNFAILURE';

export const KPIDISABLE = 'KPIDISABLE';
export const KPIDISABLEREQUEST = 'KPIDISABLEREQUEST';
export const KPIDISABLESUCCESS = 'KPIDISABLESUCCESS';
export const KPIDISABLEFAILURE = 'KPIDISABLEFAILURE';
