// Redux action constants.

// Data source constants.
export const DATASOURCE = 'DATASOURCE';
export const DATASOURCEREQUEST = 'DATASOURCEREQUEST';
export const DATASOURCESUCCESS = 'DATASOURCESUCCESS';
export const DATASOURCEFAILURE = 'DATASOURCEFAILURE';

export const CONNECTIONTYPE = 'CONNECTIONTYPE';
export const CONNECTIONTYPEREQUEST = 'CONNECTIONTYPEREQUEST';
export const CONNECTIONTYPESUCCESS = 'CONNECTIONTYPESUCCESS';
export const CONNECTIONTYPEFAILURE = 'CONNECTIONTYPEFAILURE';

export const TESTCONNECTION = 'TESTCONNECTION';
export const TESTCONNECTIONREQUEST = 'TESTCONNECTIONREQUEST';
export const TESTCONNECTIONSUCCESS = 'TESTCONNECTIONSUCCESS';
export const TESTCONNECTIONFAILURE = 'TESTCONNECTIONFAILURE';

export const CREATEDATASOURCE = 'CREATEDATASOURCE';
export const CREATEDATASOURCEREQUEST = 'CREATEDATASOURCEREQUEST';
export const CREATEDATASOURCESUCCESS = 'CREATEDATASOURCESUCCESS';
export const CREATEDATASOURCEFAILURE = 'CREATEDATASOURCEFAILURE';
// KPI Explorer constans.
export const KPIEXPLORER = 'KPIEXPLORER';
export const KPIEXPLORERREQUEST = 'KPIEXPLORERREQUEST';
export const KPIEXPLORERSUCCESS = 'KPIEXPLORERSUCCESS';
export const KPIEXPLORERFAILURE = 'KPIEXPLORERFAILURE';

export const KPIEXPLORERFORM = 'KPIEXPLORERFORM';
export const KPIEXPLORERFORMREQUEST = 'KPIEXPLORERFORMREQUEST';
export const KPIEXPLORERFORMSUCCESS = 'KPIEXPLORERFORMSUCCESS';
export const KPIEXPLORERFORMFAILURE = 'KPIEXPLORERFORMFAILURE';
export const SCHEMAAVAILABILITYSUCCESS = 'SCHEMAAVAILABILITYSUCCESS';
export const SCHEMALISTSUCCESS = 'SCHEMALISTSUCCESS';
export const SCHEMALISTREQUEST = 'SCHEMALISTREQUEST';
export const TABLELISTONSCHEMASUCCESS = 'TABLELISTONSCHEMASUCCESS';
export const TABLEINFODATAREQUEST = 'TABLEINFODATAREQUEST';
export const TABLEINFODATASUCCESS = 'TABLEINFODATASUCCESS';
export const TABLEINFODATAFAILURE = 'TABLEINFODATAFAILURE';
export const SCHEMAAVAILABILITYFAILURE = 'SCHEMAAVAILABILITYFAILURE';
export const GETALLSCHEMALISTFAILURE = 'GETALLSCHEMALISTFAILURE';
export const SCHEMAAVAILABILTYREQUEST = 'SCHEMAAVAILABILTYREQUEST';
export const TABLELISTONSCHEMAREQUEST = 'TABLELISTONSCHEMAREQUEST';
export const TABLELISTONSCHEMAFAILURE = 'TABLELISTONSCHEMAFAILURE';

export const KPIEXPLORERFIELDREQUEST = 'KPIEXPLORERFIELDREQUEST';
export const KPIEXPLORERFIELDSUCCESS = 'KPIEXPLORERFIELDSUCCESS';
export const KPIEXPLORERFIELDFAILURE = 'KPIEXPLORERFIELDFAILURE';

export const KPIEXPLORERSUBMITREQUEST = 'KPIEXPLORERSUBMITREQUEST';
export const KPIEXPLORERSUBMITSUCCESS = 'KPIEXPLORERSUBMITSUCCESS';
export const KPIEXPLORERSUBMITFAILURE = 'KPIEXPLORERSUBMITFAILURE';

export const DELETEDATASOURCE = 'DELETEDATASOURCE';
export const DELETEDATASOURCEREQUEST = 'DELETEDATASOURCEREQUEST';
export const DELETEDATASOURCESUCSESS = 'DELETEDATASOURCESUCCESS';
export const DELETEDATASOURCEFAILURE = 'DELETEDATASOURCEFAILURE';

export const DASHBOARDSIDEBAR = 'DASHBOARDSIDEBAR';
export const DASHBOARDSIDEBARREQUEST = 'DASHBOARDSIDEBARREQUEST';
export const DASHBOARDSIDEBARSUCCESS = 'DASHBOARDSIDEBARSUCCESS';
export const DASHBOARDSIDEBARFAILURE = 'DASHBOARDSIDEBARFAILURE';

export const DASHBOARDAGGREGATION = 'DASHBOARDAGGREGATION';
export const DASHBOARDAGGREGATIONSUCCESS = 'DASHBOARDAGGREGATION';
export const DASHBOARDAGGREGATIONREQUEST = 'DASHBOARDAGGREGATIONREQUEST';
export const DASHBOARDAGGREGATIONFAILURE = 'DASHBOARDAGGREGATIONFAILURE';

export const DASHBOARDLINECHART = 'DASHBOARDLINECHART';
export const DASHBOARDLINECHARTREQUEST = 'DASHBOARDLINECHARTREQUEST';
export const DASHBOARDLINECHARTSUCCESS = 'DASHBOARDLINECHARTSUCCESS';
export const DASHBOARDLINECHARTFAILURE = 'DASHBOARDLINECHARTFAILURE';

export const DASHBOARDRCAANALYSIS = 'DASBOARDRCAANALYSIS';
export const DASHBOARDRCAANALYSISREQUEST = 'DASHBOARDRCAANALYSISREQUEST';
export const DASHBOARDRCAANALYSISSUCCESS = 'DASHBOARDRCAANALYSISSUCCESS';
export const DASHBOARDRCAANALYSISFAILURE = 'DASHBOARDRCAANALYSISFAILURE';

export const DASHBOARDDIMENSION = 'DASHBOARDDIMENSION';
export const DASHBOARDDIMENSIONREQUEST = 'DASHBOARDDIMENSIONREQUEST';
export const DASHBOARDDIMENSIONSUCCESS = 'DASHBOARDDIMENSIONSUCCESS';
export const DASHBOARDDIMENSIONFAILURE = 'DASHBOARDDIMENSIONFAILURE';

export const DASHBOARDHIERARCHICAL = 'DASHBOARDHIERARCHICAL';
export const DASHBOARDHIERARCHICALSUCCESS = 'DASHBOARDHIERARCHICALSUCCESS';
export const DASHBOARDHIERARCHICALREQUEST = 'DASHBOARDHIERARCHICALREQUEST';
export const DASHBOARDHIERARCHICALFAILURE = 'DASHBOARDHIERARCHICALFAILURE';

export const ONBOARDING = 'ONBOARDING';
export const ONBOARDINGREQUEST = 'ONBOARDINGREQUEST';
export const ONBOARDINGSUCCESS = 'ONBOARDINGSUCCESS';
export const ONBOARDINGFAILURE = 'ONBOARDINGFAILURE';

export const TESTQUERY = 'TESTQUERY';
export const TESTQUERYREQUEST = 'TESTQUERYREQUEST';
export const TESTQUERYSUCCESS = 'TESTQUERYSUCCESS';
export const TESTQUERYFAILURE = 'TESTQUERYFAILURE';

export const ANOMALYDETECTION = 'ANOMALYDETECTION';
export const ANOMALYDETECTIONREQUEST = 'ANOMALYDETECTIONREQUEST';
export const ANOMALYDETECTIONSUCCESS = 'ANOMALYDETECTIONSUCCESS';
export const ANOMALYDETECTIONFAILURE = 'ANOMALYDETECTIONFAILURE';

export const ANOMALYDATAQUALITY = 'ANOMALYDATAQUALITY';
export const ANOMALYDATAQUALITYREQUEST = 'ANOMALYDATAQUALITYREQUEST';
export const ANOMALYDATAQUALITYSUCCESS = 'ANOMALYDATAQUALITYSUCCESS';
export const ANOMALYDATAQUALITYFAILURE = 'ANOMALYDATAQUALITYFAILURE';

export const ANOMALYDRILLDOWN = 'ANOMALYDRILLDOWN';
export const ANOMALYDRILLDOWNREQUEST = 'ANOMALYDRILLDOWNREQUEST';
export const ANOMALYDRILLDOWNSUCCESS = 'ANOMALYDRILLDOWNSUCCESS';
export const ANOMALYDRILLDOWNFAILURE = 'ANOMALYDRILLDOWNFAILURE';

export const KPIDISABLE = 'KPIDISABLE';
export const KPIDISABLEREQUEST = 'KPIDISABLEREQUEST';
export const KPIDISABLESUCCESS = 'KPIDISABLESUCCESS';
export const KPIDISABLEFAILURE = 'KPIDISABLEFAILURE';

export const ALERTEMAIL = ' ALERTEMAIL';
export const ALERTEMAILREQUEST = 'ALERTEMAILREQUEST';
export const ALERTEMAILSUCCESS = 'ALERTEMAILSUCCESS';
export const ALERTEMAILFAILURE = 'ALERTEMAILFAILURE';

export const CHANNELSTATUS = 'CHANNELSTATUS';
export const CHANNELSTATUSREQUEST = 'CHANNELSTATUSREQUEST';
export const CHANNELSTATUSSUCCESS = 'CHANNELSTATUSSUCCESS';
export const CHANNERSTATUSFAILURE = 'CHANNELSTATUSFAILURE';

export const EDITCHANNEL = 'EDITCHANNEL';
export const EDITCHANNELREQUEST = 'EDITCHANNELREQUEST';
export const EDITCHANNELSUCCESS = 'EDITCHANNELSUCCESS';
export const EDITCHANNELFAILURE = 'EDITCHANNELFAILURE';

export const KPISETTING = 'KPISETTING';
export const KPISETTINGREQUEST = 'KPISETTINGREQUEST';
export const KPISETTINGSUCCESS = 'KPISETTINGSUCCESS';
export const KPISETTINGFAILURE = 'KPISETTINGFAILURE';

export const KPIEDIT = 'KPIEDIT';
export const KPIEDITREQUEST = 'KPIEDITREQUEST';
export const KPIEDITSUCCESS = 'KPIEDITSUCCESS';
export const KPIEDITFAILURE = 'KPIEDITFAILURE';

export const KPIFORMEDIT_META_INFO = 'KPIFORMEDIT';
export const KPIFORMEDITREQUEST_META_INFO = 'KPIFORMEDITREQUEST';
export const KPIFORMEDITSUCCESS_META_INFO = 'KPIFORMEDITSUCCESS';
export const KPIFORMEDITFAILURE_META_INFO = 'KPIFORMEDITFAILURE';

export const KPIEDITDATA = 'KPIEDITDATA';
export const KPIEDITDATAREQUEST = 'KPIEDITDATAREQUEST';
export const KPIEDITDATASUCCESS = 'KPIEDITDATASUCCESS';
export const KPIEDITDATAFAILURE = 'KPIEDITDATAFAILURE';

export const KPIUPDATE = 'KPIUPDATE';
export const KPIUPDATEREQUEST = 'KPIUPDATEREQUEST';
export const KPIUPDATESUCCESS = 'KPIUPDATESUCCESS';
export const KPIUPDATEFAILURE = 'KPIUPDATEFAILURE';

export const DATASOURCE_META_INFO = 'DATASOURCE_META_INFO';
export const DATASOURCE_META_INFO_REQUEST = 'DATASOURCE_META_INFO_REQUEST';
export const DATASOURCE_META_INFO_SUCCESS = 'DATASOURCE_META_INFO_SUCCESS';
export const DATASOURCE_META_INFO_FAILURE = 'DATASOURCE_META_INFO_FAILURE';

export const DATASOURCEEDITDATA = 'DATASOURCEEDITDATA';
export const DATASOURCEEDITDATAREQUEST = 'DATASOURCEEDITDATAREQUEST';
export const DATASOURCEEDITDATASUCCESS = 'DATASOURCEEDITDATASUCCESS';
export const DATASOURCEEDITDATAFAILURE = 'DATASOURCEEDITDATAFAILURE';

export const DATASOURCEUPDATE = 'DATASOURCEUPDATE';
export const DATASOURCEUPDATEREQUEST = 'DATASOURCEUPDATEREQUEST';
export const DATASOURCEUPDATESUCCESS = 'DATASOURCEUPDATESUCCESS';
export const DATASOURCEUPDATEFAILURE = 'DATASOURCEUPDATEFAILURE';

export const EMAIL_META_INFO = 'EMAIL_META_INFO';
export const EMAIL_META_INFO_REQUEST = 'EMAIL_META_INFO_REQUEST';
export const EMAIL_META_INFO_SUCCESS = 'EMAIL_META_INFO_SUCCESS';
export const EMAIL_META_INFO_FAILURE = 'EMAIL_META_INFO_FAILURE';

export const SLACK_META_INFO = 'SLACK_META_INFO';
export const SLACK_META_INFO_REQUEST = 'SLACK_META_INFO_REQUEST';
export const SLACK_META_INFO_SUCCESS = 'SLACK_META_INFO_SUCCESS';
export const SLACK_META_INFO_FAILURE = 'SLACK_META_INFO_FAILURE';

export const HOMEKPIVIEW = 'HOME_KPI_VIEW';
export const HOMEKPIVIEWREQUEST = 'HOMEKPIVIEWREQUEST';
export const HOMEKPIVIEWSUCCESS = 'HOMEKPIVIEWSUCCESS';
export const HOMEKPIVIEWFAILURE = 'HOMEKPIVIEWFAILURE';

export const ALERTS = 'ALERTS';
export const ALERTSREQUEST = 'ALERTSREQUEST';
export const ALERTSSUCCESS = 'ALERTSSUCCESS';
export const ALERTSFAILURE = 'ALERTSFAILURE';

export const CREATEKPIALERT = 'CREATEKPIALERT';
export const CREATEKPIALERTREQUEST = 'CREATEKPIALERTREQUEST';
export const CREATEKPIALERTSUCCESS = 'CREATEKPIALERTSUCCESS';
export const CREATEKPIALERTFAILURE = 'CREATEKPIALERTFAILURE';

export const KPI_ALERT_META_INFO = 'KPIALERTMETAINFO';
export const KPI_ALERT_META_INFO_REQUEST = 'KPIALERTMETAINFOREQUEST';
export const KPI_ALERT_META_INFO_SUCCESS = 'KPIALERTMETAINFOSUCCESS';
export const KPI_ALERT_META_INFO_FAILURE = 'KPIALERTMETAINFOFAILURE';

export const KPIALERTEDIT = 'KPIALERTEDIT';
export const KPIALERTEDITREQUEST = 'KPIALERTEDITREQUEST';
export const KPIALERTEDITSUCCESS = 'KPIALERTEDITSUCCESS';
export const KPIALERTEDITFAILURE = 'KPIALERTEDITFAILURE';

export const KPIALERTUPDATE = 'KPIALERTUPDATE';
export const KPIALERTUPDATEREQUEST = 'KPIALERTUPDATEREQUEST';
export const KPIALERTUPDATESUCCESS = 'KPIALERTUPDATESUCCESS';
export const KPIALERTUPDATEFAILURE = 'KPIALERTUPDATEFAILURE';

export const KPIALERTDISABLE = 'KPIALERTDISABLE';
export const KPIALERTDISABLEREQUEST = 'KPIALERTDISABLEREQUEST';
export const KPIALERTDISABLESUCCESS = 'KPIALERTDISABLESUCCESS';
export const KPIALERTDISABLEFAILURE = 'KPIALERTDISABLEFAILURE';

export const KPIALERTENABLE = 'KPIALERTENABLE';
export const KPIALERTENABLEREQUEST = 'KPIALERTENABLEREQUEST';
export const KPIALERTENABLERESPONSE = 'KPIALERTENABLERESPONSE';
export const KPIALERTENABLEFAILURE = 'KPIALERTENABLEFAILURE';

export const KPIALERTDELETE = 'KPIALERTDELETE';
export const KPIALERTDELETEREQUEST = 'KPIALERTDELETEREQUEST';
export const KPIALERTDELETERESPONSE = 'KPIALERTDELETERESPONSE';
export const KPIALERTDELETEFAILURE = 'KPIALERTDELETEFAILURE';

export const ANOMALYSETTING = 'ANOMALYSETTING';
export const ANOMALYSETTINGREQUEST = 'ANOMALYSETTINGREQUEST';
export const ANOMALYSETTINGSUCCESS = 'ANOMALYSETTINGSUCCESS';
export const ANOMALYSETTINGFAILURE = 'ANOMALYSETTINGFAILURE';

export const SETTING_META_INFO = 'SETTINGMETAINFO';
export const SETTING_META_INFO_REQUEST = 'SETTINGMETAINFOREQUEST';
export const SETTING_META_INFO_SUCCESS = 'SETTINGMETAINFOSUCCESS';
export const SETTING_META_INFO_FAILURE = 'SETTINGMETAINFOFAILURE';

export const DASHBOARD = 'DASHBOARD';
export const DASHBOARDREQUEST = 'DASHBOARDREQUEST';
export const DASHBOARDSUCCESS = 'DASHBOARDSUCCESS';
export const DASHBOARDFAILURE = 'DASHBOARDFAILURE';

export const DASHBOARDDELETE = 'DASHBOARDDELETE';
export const DASHBOARDDELETEREQUEST = 'DASHBOARDDELETEREQUEST';
export const DASHBOARDDELETERESPONSE = 'DASHBOARDDELETERESPONSE';
export const DASHBOARDDELETEFAILURE = 'DASHBOARDDELETEFAILURE';

export const DASHBOARDCREATE = 'DASHBOARDCREATE';
export const DASHBOARDCREATEREQUST = 'DASHBOARDCREATEREQUEST';
export const DASHBOARDCREATESUCCESS = 'DASHBOARDCREATESUCCESS';
export const DASHBOARDCREATEFAILURE = 'DASHBOARDCREATEFAILURE';

export const DASHBOARDEDIT = 'DASHBOARDEDIT';
export const DASHBOARDEDITREQUEST = 'DASHBOARDEDITREQUEST';
export const DASHBOARDEDITRESPONSE = 'DASHBOARDEDITRESPONSE';
export const DASHBOARDEDITFAILURE = 'DASHBOARDEDITFAILURE';

export const DASHBOARDUPDATE = 'DASHBOARDUPDATE';
export const DASHBOARDUPDATEREQUEST = 'DASHBOARDUPDATEREQUEST';
export const DASHBOARDUPDATESUCCESS = 'DASHBOARDUPDATESUCCESS';
export const DASHBOARDUPDATEFAILURE = 'DASHBOARDUPDATEFAILURE';

export const ONBOARD_ORGANIZATION = 'ONBOARDORGANIZATION';
export const ONBOARD_ORGANIZATION_REQUEST = 'ONBOARDORGANIZATIONREQUEST';
export const ONBOARD_ORGANIZATION_SUCCESS = 'ONBOARDORGANIZATIONSUCCESS';
export const ONBOARD_ORGANIZATION_FAILURE = 'ONBOARDORGANIZATIONFAILURE';
export const ONBOARD_ORGANIZATION_UPDATE_SUCCESS =
  'ONBOARDORGANIZATIONUPDATESUCCESS';

export const DASHBOARD_CONFIG = 'DASHBOARD_CONFIG';
export const DASHBOARD_CONFIG_REQUEST = 'DASHBOARD_CONFIG_REQUEST';
export const DASHBOARD_CONFIG_SUCCESS = 'DASHBOARD_CONFIG_SUCCESS';
export const DASHBOARD_CONFIG_FAILURE = 'DASHBOARD_CONFIG_FAILURE';

export const GLOBAL_SETTING = 'GLOBAL_SETTING';
export const GLOBAL_SETTING_REQUEST = 'GLOBAL_SETTING_REQUEST';
export const GLOBAL_SETTING_SUCCESS = 'GLOBAL_SETTING_SUCCESS';
export const GLOBAL_SETTING_FALIURE = 'GLOBAL_SETTING_FAILURE';

export const TIME_CUTS_REQUEST = 'TIME_CUTS_REQUEST';
export const TIME_CUTS_SUCCESS = 'TIME_CUTS_SUCCESS';
export const TIME_CUTS_FALIURE = 'TIME_CUTS_FAILURE';
export const VERSION_SETTING_REQUEST = 'VERSION_SETTING_REQUEST';
export const VERSION_SETTING_SUCCESS = 'VERSION_SETTING_SUCCESS';
export const VERSION_SETTING_FALIURE = 'VERSION_SETTING_FAILURE';

export const SAVE_REPORT_SETTINGTIME_REQUEST =
  'SAVE_REPORT_SETTINGTIME_REQUEST';
export const SAVE_REPORT_SETTINGTIME_FAILURE =
  'SAVE_REPORT_SETTINGTIME_FAILURE';
export const SAVE_REPORT_SETTINGTIME_SUCCESS =
  'SAVE_REPORT_SETTINGTIME_SUCCESS';

export const GET_REPORT_SETTINGTIME_REQUEST = 'GET_REPORT_SETTINGTIME_REQUEST';
export const GET_REPORT_SETTINGTIME_SUCCESS = 'GET_REPORT_SETTINGTIME_SUCCESS';
export const GET_REPORT_SETTINGTIME_FAILURE = 'GET_REPORT_SETTINGTIME_FAILURE';

export const SUPPORTEDAGGSUCCESS = 'SUPPORTEDAGGSUCCESS';
export const RETRAINFAILURE = 'RETRAINFAILURE';
export const RETRAINREQUEST = 'RETRAINREQUEST';
export const RETRAINSUCCESS = 'RETRAINSUCCESS';
