# build environment
FROM node:14-alpine as chaosgenius-webapp-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.3 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:1.21.3-alpine
COPY --from=chaosgenius-webapp-build /app/build /usr/share/nginx/html
COPY nginx/nginx-default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
