version: "3.7"
#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging: &default-logging
  options:
    fluentd-address: localhost:24224
    fluentd-async: "true"
  driver: fluentd
x-version:
  &chaosgenius-version
  CHAOSGENIUS_VERSION_POSTFIX=fluentd-compose

services:
  chaosgenius-fluentd:
    container_name: chaosgenius-fluentd
    image: fluent/fluentd:latest
    restart: unless-stopped
    environment:
      - FLUENTD_CONF=log.conf
      - FLUENT_UID=0
    ports:
      - 24224:24224
    volumes:
      - ./setup/fluentd/log.conf:/fluentd/etc/log.conf
      - ./logs:/var/log/fluent

  chaosgenius-server:
    container_name: chaosgenius-server
    image: chaosgenius/chaosgenius-server:latest
    command: sh setup/run-backend-docker.sh
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - chaosgenius-db
      - chaosgenius-fluentd
    environment:
      - *chaosgenius-version
      - IN_DOCKER=True
      - AIRBYTE_ENABLED=${AIRBYTE_ENABLED}
      - REACT_APP_IS_DEMO=${REACT_APP_IS_DEMO}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SEND_FILE_MAX_AGE_DEFAULT=${SEND_FILE_MAX_AGE_DEFAULT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - META_DATABASE=${META_DATABASE}
      - DATA_DATABASE=${DATA_DATABASE}
      - DATABASE_URL_CG_DB=${DATABASE_URL_CG_DB}
      - INTEGRATION_SERVER=${INTEGRATION_SERVER}
      - INTEGRATION_DB_HOST=${INTEGRATION_DB_HOST}
      - INTEGRATION_DB_USERNAME=${INTEGRATION_DB_USERNAME}
      - INTEGRATION_DB_PASSWORD=${INTEGRATION_DB_PASSWORD}
      - INTEGRATION_DB_PORT=${INTEGRATION_DB_PORT}
      - INTEGRATION_DATABASE=${INTEGRATION_DATABASE}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CACHE_DEFAULT_TIMEOUT=${CACHE_DEFAULT_TIMEOUT}
      - MULTIDIM_ANALYSIS_FOR_ANOMALY=${MULTIDIM_ANALYSIS_FOR_ANOMALY}
      - MAX_SUBDIM_CARDINALITY=${MAX_SUBDIM_CARDINALITY}
      - TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN=${TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN}
      - MIN_DATA_IN_SUBGROUP=${MIN_DATA_IN_SUBGROUP}
      - TOP_SUBDIMENSIONS_FOR_ANOMALY=${TOP_SUBDIMENSIONS_FOR_ANOMALY}
      - MAX_ROWS_IN_KPI=${MAX_ROWS_IN_KPI}
      - MAX_FILTER_SUBGROUPS_ANOMALY=${MAX_FILTER_SUBGROUPS_ANOMALY}
      - MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS=${MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS}
      - MAX_ANOMALY_SLACK_DAYS=${MAX_ANOMALY_SLACK_DAYS}
      - DAYS_OFFSET_FOR_ANALTYICS=${DAYS_OFFSET_FOR_ANALTYICS}
      - HOURS_OFFSET_FOR_ANALTYICS=${HOURS_OFFSET_FOR_ANALTYICS}
      - DEEPDRILLS_HTABLE_MAX_PARENTS=${DEEPDRILLS_HTABLE_MAX_PARENTS}
      - DEEPDRILLS_HTABLE_MAX_CHILDREN=${DEEPDRILLS_HTABLE_MAX_CHILDREN}
      - DEEPDRILLS_HTABLE_MAX_DEPTH=${DEEPDRILLS_HTABLE_MAX_DEPTH}
      - SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES=${SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES}
      - DEEPDRILLS_ENABLED=${DEEPDRILLS_ENABLED}
      - TIMEZONE=${TIMEZONE}
      - REACT_APP_EVENT_ALERT=${REACT_APP_EVENT_ALERT}
      - SENTRY_DSN=${SENTRY_DSN}
      - CHAOSGENIUS_ENTERPRISE_EDITION_KEY=${CHAOSGENIUS_ENTERPRISE_EDITION_KEY}
      - CHAOSGENIUS_WEBAPP_URL=${CHAOSGENIUS_WEBAPP_URL}
      - CORS_ENABLED=${CORS_ENABLED}
    logging: *default-logging

  chaosgenius-webapp:
    container_name: chaosgenius-webapp
    image: chaosgenius/chaosgenius-webapp:latest
    command: >
      sh -c "npx react-inject-env set -d ./ &&
             nginx -g 'daemon off;'"
    restart: unless-stopped
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d/
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - REACT_APP_DISABLE_TELEMETRY=${REACT_APP_DISABLE_TELEMETRY}
      - REACT_APP_EVENT_ALERT=${REACT_APP_EVENT_ALERT}
      - REACT_APP_IS_DEMO=${REACT_APP_IS_DEMO}
    depends_on:
      - chaosgenius-server
      - chaosgenius-fluentd
    logging: *default-logging

  chaosgenius-db:
    container_name: chaosgenius-db
    image: postgres:13
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "chaosgenius_data", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/cg-db-setup:/docker-entrypoint-initdb.d/
      - cg-db:/var/lib/postgresql/data
    depends_on:
      - chaosgenius-fluentd
    logging: *default-logging

  chaosgenius-redis:
    container_name: chaosgenius-redis
    image: "redis:6.2-alpine"
    restart: unless-stopped
    depends_on:
      - chaosgenius-fluentd
    logging: *default-logging
    
  chaosgenius-scheduler:
    container_name: chaosgenius-scheduler
    image: chaosgenius/chaosgenius-server:latest
    command: celery -A run.celery beat --loglevel=DEBUG
    restart: unless-stopped
    environment:
      - IN_DOCKER=True
      - AIRBYTE_ENABLED=${AIRBYTE_ENABLED}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SEND_FILE_MAX_AGE_DEFAULT=${SEND_FILE_MAX_AGE_DEFAULT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - META_DATABASE=${META_DATABASE}
      - DATA_DATABASE=${DATA_DATABASE}
      - DATABASE_URL_CG_DB=${DATABASE_URL_CG_DB}
      - INTEGRATION_SERVER=${INTEGRATION_SERVER}
      - INTEGRATION_DB_HOST=${INTEGRATION_DB_HOST}
      - INTEGRATION_DB_USERNAME=${INTEGRATION_DB_USERNAME}
      - INTEGRATION_DB_PASSWORD=${INTEGRATION_DB_PASSWORD}
      - INTEGRATION_DB_PORT=${INTEGRATION_DB_PORT}
      - INTEGRATION_DATABASE=${INTEGRATION_DATABASE}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - REACT_APP_EVENT_ALERT=${REACT_APP_EVENT_ALERT}
      - SENTRY_DSN=${SENTRY_DSN}
      - CHAOSGENIUS_ENTERPRISE_EDITION_KEY=${CHAOSGENIUS_ENTERPRISE_EDITION_KEY}
      - CHAOSGENIUS_WEBAPP_URL=${CHAOSGENIUS_WEBAPP_URL}
      - METADATA_SYNC_TIME=${METADATA_SYNC_TIME}
    depends_on:
      - chaosgenius-redis
      - chaosgenius-fluentd
    logging: *default-logging
  
  chaosgenius-worker-analytics:
    container_name: chaosgenius-worker-analytics
    image: chaosgenius/chaosgenius-server:latest
    command: celery -A run.celery worker --loglevel=INFO --concurrency=2 -P processes -Q anomaly-rca
    restart: unless-stopped
    environment:
      - IN_DOCKER=True
      - AIRBYTE_ENABLED=${AIRBYTE_ENABLED}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SEND_FILE_MAX_AGE_DEFAULT=${SEND_FILE_MAX_AGE_DEFAULT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - META_DATABASE=${META_DATABASE}
      - DATA_DATABASE=${DATA_DATABASE}
      - DATABASE_URL_CG_DB=${DATABASE_URL_CG_DB}
      - INTEGRATION_SERVER=${INTEGRATION_SERVER}
      - INTEGRATION_DB_HOST=${INTEGRATION_DB_HOST}
      - INTEGRATION_DB_USERNAME=${INTEGRATION_DB_USERNAME}
      - INTEGRATION_DB_PASSWORD=${INTEGRATION_DB_PASSWORD}
      - INTEGRATION_DB_PORT=${INTEGRATION_DB_PORT}
      - INTEGRATION_DATABASE=${INTEGRATION_DATABASE}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - MULTIDIM_ANALYSIS_FOR_ANOMALY=${MULTIDIM_ANALYSIS_FOR_ANOMALY}
      - MAX_SUBDIM_CARDINALITY=${MAX_SUBDIM_CARDINALITY}
      - TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN=${TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN}
      - MIN_DATA_IN_SUBGROUP=${MIN_DATA_IN_SUBGROUP}
      - TOP_SUBDIMENSIONS_FOR_ANOMALY=${TOP_SUBDIMENSIONS_FOR_ANOMALY}
      - MAX_ROWS_IN_KPI=${MAX_ROWS_IN_KPI}
      - MAX_FILTER_SUBGROUPS_ANOMALY=${MAX_FILTER_SUBGROUPS_ANOMALY}
      - MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS=${MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS}
      - MAX_ANOMALY_SLACK_DAYS=${MAX_ANOMALY_SLACK_DAYS}
      - DAYS_OFFSET_FOR_ANALTYICS=${DAYS_OFFSET_FOR_ANALTYICS}
      - HOURS_OFFSET_FOR_ANALTYICS=${HOURS_OFFSET_FOR_ANALTYICS}
      - DEEPDRILLS_HTABLE_MAX_PARENTS=${DEEPDRILLS_HTABLE_MAX_PARENTS}
      - DEEPDRILLS_HTABLE_MAX_CHILDREN=${DEEPDRILLS_HTABLE_MAX_CHILDREN}
      - DEEPDRILLS_HTABLE_MAX_DEPTH=${DEEPDRILLS_HTABLE_MAX_DEPTH}
      - SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES=${SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES}
      - DEEPDRILLS_ENABLED=${DEEPDRILLS_ENABLED}
      - TIMEZONE=${TIMEZONE}
      - REACT_APP_EVENT_ALERT=${REACT_APP_EVENT_ALERT}
      - SENTRY_DSN=${SENTRY_DSN}
      - CHAOSGENIUS_ENTERPRISE_EDITION_KEY=${CHAOSGENIUS_ENTERPRISE_EDITION_KEY}
      - CHAOSGENIUS_WEBAPP_URL=${CHAOSGENIUS_WEBAPP_URL}
    depends_on:
      - chaosgenius-redis
      - chaosgenius-db
      - chaosgenius-fluentd
    logging: *default-logging

  chaosgenius-worker-alerts:
    container_name: chaosgenius-worker-alerts
    image: chaosgenius/chaosgenius-server:latest
    command: celery -A run.celery worker --loglevel=INFO --concurrency=2 -P processes -Q alerts
    restart: unless-stopped
    environment:
      - IN_DOCKER=True
      - AIRBYTE_ENABLED=${AIRBYTE_ENABLED}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - SEND_FILE_MAX_AGE_DEFAULT=${SEND_FILE_MAX_AGE_DEFAULT}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - META_DATABASE=${META_DATABASE}
      - DATA_DATABASE=${DATA_DATABASE}
      - DATABASE_URL_CG_DB=${DATABASE_URL_CG_DB}
      - INTEGRATION_SERVER=${INTEGRATION_SERVER}
      - INTEGRATION_DB_HOST=${INTEGRATION_DB_HOST}
      - INTEGRATION_DB_USERNAME=${INTEGRATION_DB_USERNAME}
      - INTEGRATION_DB_PASSWORD=${INTEGRATION_DB_PASSWORD}
      - INTEGRATION_DB_PORT=${INTEGRATION_DB_PORT}
      - INTEGRATION_DATABASE=${INTEGRATION_DATABASE}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CACHE_DEFAULT_TIMEOUT=${CACHE_DEFAULT_TIMEOUT}
      - MULTIDIM_ANALYSIS_FOR_ANOMALY=${MULTIDIM_ANALYSIS_FOR_ANOMALY}
      - MAX_SUBDIM_CARDINALITY=${MAX_SUBDIM_CARDINALITY}
      - TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN=${TOP_DIMENSIONS_FOR_ANOMALY_DRILLDOWN}
      - MIN_DATA_IN_SUBGROUP=${MIN_DATA_IN_SUBGROUP}
      - TOP_SUBDIMENSIONS_FOR_ANOMALY=${TOP_SUBDIMENSIONS_FOR_ANOMALY}
      - MAX_ROWS_IN_KPI=${MAX_ROWS_IN_KPI}
      - MAX_FILTER_SUBGROUPS_ANOMALY=${MAX_FILTER_SUBGROUPS_ANOMALY}
      - MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS=${MAX_SUMMARY_DEEPDRILLS_SLACK_DAYS}
      - MAX_ANOMALY_SLACK_DAYS=${MAX_ANOMALY_SLACK_DAYS}
      - DAYS_OFFSET_FOR_ANALTYICS=${DAYS_OFFSET_FOR_ANALTYICS}
      - HOURS_OFFSET_FOR_ANALTYICS=${HOURS_OFFSET_FOR_ANALTYICS}
      - DEEPDRILLS_HTABLE_MAX_PARENTS=${DEEPDRILLS_HTABLE_MAX_PARENTS}
      - DEEPDRILLS_HTABLE_MAX_CHILDREN=${DEEPDRILLS_HTABLE_MAX_CHILDREN}
      - DEEPDRILLS_HTABLE_MAX_DEPTH=${DEEPDRILLS_HTABLE_MAX_DEPTH}
      - SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES=${SUMMARY_DEEPDRILLS_ENABLED_TIME_RANGES}
      - DEEPDRILLS_ENABLED=${DEEPDRILLS_ENABLED}
      - REACT_APP_EVENT_ALERT=${REACT_APP_EVENT_ALERT}
      - SENTRY_DSN=${SENTRY_DSN}
      - CHAOSGENIUS_ENTERPRISE_EDITION_KEY=${CHAOSGENIUS_ENTERPRISE_EDITION_KEY}
      - CHAOSGENIUS_WEBAPP_URL=${CHAOSGENIUS_WEBAPP_URL}
      - TIMEZONE=${TIMEZONE}
    depends_on:
      - chaosgenius-redis
      - chaosgenius-db
      - chaosgenius-fluentd
    logging: *default-logging

volumes:
  cg-db:
    name: ${CG_DB_DOCKER_MOUNT}
