"""remove rca_time field from kpi

Revision ID: 1f762aa71f7d
Revises: 9ff4ef7e6d7d
Create Date: 2021-09-22 15:14:27.977261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f762aa71f7d'
down_revision = '9ff4ef7e6d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'rca_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('rca_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
