"""Add Count column & upgrade step

Revision ID: 27d55d03f753
Revises: e3625265a039
Create Date: 2022-06-08 14:29:57.525557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d55d03f753'
down_revision = 'e3625265a039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kpi", sa.Column("count_column", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    update_query = """
                UPDATE kpi
                SET count_column = 'count'
                WHERE data_source IN
                ( SELECT id FROM data_source WHERE connection_type = 'Druid' )
            """
    op.execute(update_query)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'count_column')
    # ### end Alembic commands ###
