"""added schema column in kpi table

Revision ID: 289afabc70d3
Revises: f7d137e094dd
Create Date: 2021-12-17 13:15:18.388447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289afabc70d3'
down_revision = 'f7d137e094dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('schema_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'schema_name')
    # ### end Alembic commands ###
