"""added schema column in kpi table

Revision ID: 289afabc70d3
Revises: 7c504acbf3c4
Create Date: 2021-12-17 13:15:18.388447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289afabc70d3'
down_revision = '7c504acbf3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('schema_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'schema_name')
    # ### end Alembic commands ###
