"""add_yhat_anomaly

Revision ID: 4dc7b0472e64
Revises: d8a19036bd15
Create Date: 2022-09-21 21:54:31.981119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc7b0472e64'
down_revision = 'd8a19036bd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_data_output', sa.Column('yhat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_data_output', 'yhat')
    # ### end Alembic commands ###
