"""change in the kpi.

Revision ID: 5046711d5efe
Revises: 932136ccaf6a
Create Date: 2021-07-10 19:21:02.209713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5046711d5efe'
down_revision = '932136ccaf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('table_name', sa.Text(), nullable=False))
    op.add_column('kpi', sa.Column('metric', sa.Text(), nullable=False))
    op.drop_column('kpi', 'metric_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('metric_column', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('kpi', 'metric')
    op.drop_column('kpi', 'table_name')
    # ### end Alembic commands ###
