"""empty message

Revision ID: 5476b9c7fca7
Revises: 5757853f2a9a
Create Date: 2021-09-21 18:42:27.354162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5476b9c7fca7'
down_revision = '5757853f2a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('last_alerted', sa.DateTime(), nullable=True))
    op.alter_column('kpi', 'kpi_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('kpi', 'aggregation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi', 'aggregation',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('kpi', 'kpi_type',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('alert', 'last_alerted')
    # ### end Alembic commands ###
