"""add the alert data table

Revision ID: 5757853f2a9a
Revises: 97802c5d19df
Create Date: 2021-08-14 10:34:07.286574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5757853f2a9a'
down_revision = '97802c5d19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_name', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('data_source', sa.Integer(), nullable=True),
    sa.Column('alert_query', sa.Text(), nullable=True),
    sa.Column('alert_settings', sa.String(length=80), nullable=True),
    sa.Column('kpi', sa.Integer(), nullable=True),
    sa.Column('kpi_alert_type', sa.String(length=80), nullable=True),
    sa.Column('severity_cutoff_score', sa.Integer(), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('alert_frequency', sa.String(length=80), nullable=True),
    sa.Column('alert_channel', sa.String(length=80), nullable=True),
    sa.Column('alert_channel_conf', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    # ### end Alembic commands ###
