"""created_at for anomaly_data_output

Revision ID: 5c754059d673
Revises: 890f3e569771
Create Date: 2022-03-02 11:43:23.190821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c754059d673'
down_revision = '890f3e569771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_data_output', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_data_output', 'created_at')
    # ### end Alembic commands ###
