"""daily digests column to alert table

Revision ID: 60826e68339e
Revises: d2b01087c980
Create Date: 2022-01-17 15:01:32.129823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60826e68339e'
down_revision = 'd2b01087c980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('daily_digest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'daily_digest')
    # ### end Alembic commands ###
