"""add the kpi anomaly data table.

Revision ID: 723d35e3a80a
Revises: 5046711d5efe
Create Date: 2021-07-26 22:04:03.893383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723d35e3a80a'
down_revision = '5046711d5efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('run_anomaly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'run_anomaly')
    # ### end Alembic commands ###
