"""add the static kpi fields for demo

Revision ID: 7be54a3936d5
Revises: 213fbb63bdb6
Create Date: 2021-08-10 23:33:29.047134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be54a3936d5'
down_revision = '213fbb63bdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('is_static', sa.Boolean(), nullable=True))
    op.add_column('kpi', sa.Column('static_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'static_params')
    op.drop_column('kpi', 'is_static')
    # ### end Alembic commands ###
