"""add indexes to triggered alerts table

Revision ID: 890f3e569771
Revises: 50b793ad398a
Create Date: 2022-02-14 10:43:02.439137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f3e569771'
down_revision = '50b793ad398a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_triggered_alerts_created_at'), 'triggered_alerts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggered_alerts_created_at'), table_name='triggered_alerts')
    # ### end Alembic commands ###
