"""added timezone aware column to kpi definition

Revision ID: 8a84c573b1b6
Revises: 890f3e569771
Create Date: 2022-03-09 02:20:09.910201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a84c573b1b6'
down_revision = '890f3e569771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('timezone_aware', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'timezone_aware')
    # ### end Alembic commands ###
