"""RCA Data Table Created

Revision ID: 97802c5d19df
Revises: c0e8d68e84fa
Create Date: 2021-09-12 21:39:36.749656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97802c5d19df'
down_revision = 'c0e8d68e84fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rca_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.String(length=80), nullable=False),
    sa.Column('timeline', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('rca_data')
    # ### end Alembic commands ###
