"""add rca_time field in kpi model nullable = true

Revision ID: 9ff4ef7e6d7d
Revises: 5476b9c7fca7
Create Date: 2021-09-22 14:39:28.983470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4ef7e6d7d'
down_revision = '5476b9c7fca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('rca_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'rca_time')
    # ### end Alembic commands ###
