"""add alert_status to alert model

Revision ID: a0e6c5ce5b58
Revises: d26c98f417da
Create Date: 2021-12-06 14:45:54.011025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e6c5ce5b58'
down_revision = 'd26c98f417da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('alert_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'alert_status')
    # ### end Alembic commands ###
