"""increased length of series type in anomaly data output

Revision ID: abf0d4ab3bc9
Revises: e10b2bb6682d
Create Date: 2021-08-31 09:47:33.105211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf0d4ab3bc9'
down_revision = 'e10b2bb6682d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_data_output', 'series_type',
               existing_type=sa.String(length=80),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_data_output', 'series_type',
               existing_type=sa.String(length=500),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
