"""added anomaly config to kpi

Revision ID: c0e8d68e84fa
Revises: abf0d4ab3bc9
Create Date: 2021-09-02 09:08:21.174195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e8d68e84fa'
down_revision = 'abf0d4ab3bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('anomaly_params', sa.JSON(), nullable=True))
    op.add_column('kpi', sa.Column('anomaly_frequency', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'anomaly_frequency')
    op.drop_column('kpi', 'anomaly_params')
    # ### end Alembic commands ###
