"""empty message

Revision ID: d26c98f417da
Revises: a24d4e0bf8aa
Create Date: 2021-12-02 15:18:21.863916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26c98f417da'
down_revision = 'a24d4e0bf8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('anomaly_data_output_query_idx', 'anomaly_data_output', ['kpi_id', 'anomaly_type', 'series_type', 'data_datetime'], unique=False)
    op.create_index('rca_data_query_idx', 'rca_data', ['kpi_id', 'data_type', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rca_data_query_idx', table_name='rca_data')
    op.drop_index('anomaly_data_output_query_idx', table_name='anomaly_data_output')
    # ### end Alembic commands ###
