"""added active column to dashboard_kpi_mapper

Revision ID: d4aa58d3dc5d
Revises: f7d137e094dd
Create Date: 2021-11-23 11:18:57.068166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4aa58d3dc5d'
down_revision = 'f7d137e094dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_kpi_mapper', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_kpi_mapper', 'active')
    # ### end Alembic commands ###
