"""add include_subdims to Alert

Revision ID: d6b3cfcc1298
Revises: 27d55d03f753
Create Date: 2022-06-21 10:58:38.243902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b3cfcc1298'
down_revision = '27d55d03f753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('include_subdims', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'include_subdims')
    # ### end Alembic commands ###
