"""make scheduler_params a separate JSONB field

Revision ID: f5f55452fa58
Revises: 1f762aa71f7d
Create Date: 2021-09-28 16:48:42.834962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5f55452fa58'
down_revision = '1f762aa71f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi', sa.Column('scheduler_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi', 'scheduler_params')
    # ### end Alembic commands ###
